### ISSUE TITLE
Allow running bitwarden2hashcat against a specific data.json file

### ISSUE THREAD

**Issue by philsmd** [0x6470/bitwarden2hashcat#1]
It would be great if this tool would allow to specify the path to a specific file (like in case of a pentester who gathered some .json files that they want to "convert"):
```
python bitwarden2hashcat.py /tmp/2020_08_13_0912/client1337/data.json
```

Several `*2hashcat` and `*2john` tools allow specifying a specific file and it will be converted to a hash. This would be a great addition thx

**Comment by 0x6470** [comment]
Actually, I'm on vacation right now.
I'll get back to this in a week or two.
Have a good time!

**Comment by 0x6470** [comment]
I implemented this now with [`e455470`](https://github.com/0x6470/bitwarden2hashcat/commit/e4554702b845dbb315269090dc524dcf649f11ba).
Also, I changed the licence to BSD-3 to extend compatibility to hashcat and JTR.
I am very happy to have had the opportunity to contribute something to hashcat!
Feel free, to open another issue if neccessary.

**Comment by philsmd** [comment]
Wow.
Thank you so much.

This update is great.

Looking at the code, I just think there might be 1 single instance that doesn't work yet (but it's of course not a big deal):
what if the user tries to run this:
`bitwarden2hashcat.py /tmp/a.json /home/philsmd/Downloads/data.json /data.json`

most other `*2hashcat` or `*2john` tools allow this scenario.

This is of course a new feature request if it's currently not working... I just wanted to mention it here, because as my very tiny python understanding goes, it currently doesn't/shouldn't work with the update, right ?

Maybe you decide changing this, but again it's not a big deal.

Thank you again for this great tool and all your help/support also with explaining the algorithm etc.
Well done.

**Comment by 0x6470** [comment]
I am still very glad that I can/could help.
You're welcome.

I also implemented your suggestion, since it was just a small change and little of work.

Am looking forward to helping again!
