### ISSUE TITLE
"please install plyvel module"

### ISSUE THREAD

**Issue by mdrivera1** [0x6470/bitwarden2hashcat#2]
I had to install plyvel using anaconda cmd prompt. When I try to run python3 bitwarden2hashcat.py I keep getting "please install plyvel module." I have very little knowledge and just trying to get into my bitwarden vault after loosing the master password (may be futile).

**Comment by 0x6470** [comment]
Could you please provide the operating system you're working with. Also, what happens if you type `import plyvel` into a python prompt?

**Comment by mdrivera1** [comment]
I am using Windows and I got it to run but it keeps asking for me to do it
manually. I can not find the keyhash entry in the chrome extension to enter
the information.

**Comment by 0x6470** [comment]
Do you get to the part where you see "Inspect views background.html"?

**Comment by mdrivera1** [comment]
yes, I get to that part but then I don't see keyhash anywhere. If I open up the extension folder through file explorer, I see 000007.log which has something that says keyhash inside but it's gibberish. I'm guessing that's what I'm really trying to decipher? Sorry, I'm rubbish at all this and I locked my vault and can't get in...I'm hoping there might be a way.

**Comment by 0x6470** [comment]
The log files don't help you in that case. You should stick to the given instructions and enter the given command into the console (console tab).

**Comment by mdrivera1** [comment]
I did enter the information in the console. There must be something wrong with my setup because it only shows: 
appId: "1094285b-1f25-40e6-a9b5-5b64b3c19136"
biometricFingerprintValidated: false
lastActive: 1611418238984
lastSync_e6a3921e-656d-4171-bebd-aca4015036fe: "1970-01-01T00:00:00.000Z"
lockOption: null
passwordGenerationOptions: {ambiguous: false, capitalize: false, includeNumber: false, length: 14, lowercase: true, …}
rememberEmail: true
rememberedEmail: "XXXX"
sends_e6a3921e-656d-4171-bebd-aca4015036fe: {}
sitesLocalData: {62430b91-c977-4ae0-be96-aca401538376: {…}, c7a102ac-8cc1-499d-a6da-aca401538376: {…}, f96e3704-ef3a-4510-b1fa-aca401538376: {…}}
vaultTimeoutAction: "lock"
__proto__: Object

**Comment by 0x6470** [comment]
Thats indeed very strange. You might want to try the following in a python prompt:
```
import plyvel, os
path = "{}\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Local Extension Settings\\nngceckbapebfimnlniiiahkandclblb".format(os.getenv("userprofile"))
db = plyvel.DB(path, create_if_missing=False)
email = db.get(b"userEmail").decode().strip("\"")
keyHash = db.get(b"keyHash").decode().strip("\"")
iterations = db.get(b"kdfIterations").decode().strip("\"")
print(email, keyHash, iterations, sep="\n")
```
This is basically the automatic extraction process. You might also want to post the error message - if one occurs - so that the error can be spotted easily.

**Comment by mdrivera1** [comment]
Unfortunately, I could not figure it out.  I do not have enough technical
expertise. It doesn't seem like I'll ever be able to get into my bitwarden
account. Thank you for your responses and suggestions!
